sudo: required

language: cpp

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.20.0

before_install:
  - sudo apt-get update
  - ls -a
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
  - docker ps

script: cd tests && ./tests.sh
