version: '3.3'

services:
  exchange:
    build: .
    command: bash -c "ls -a && go run tcp_server.go matching_engine.go"
    volumes:
      - "./src:/src"
      - "./logs:/var/log/erss"
    ports:
      - "12345:12345"
    tty: true
