version: '3.3'

services:
  redis:
    image: redis
  exchange:
    build: .
    command: bash -c "ls -a && go run redis_utils.go tcp_server.go request_handler.go matching_engine.go"
    volumes:
      - "./src:/src"
      - "./logs:/var/log/erss"
    ports:
      - "12345:12345"
    tty: true
