version: '3.3'

services:
  db:
    image: postgres
  redis:
    image: redis
  exchange:
    build: .
    command: bash -c "ls -a && go install github.com/farice/EME/matching_engine && matching_engine"
    volumes:
      - "./src:/go/src/github.com/farice/EME/"
      - "./logs:/var/log/erss"
    ports:
      - "12345:12345"
    tty: true
    depends_on:
      - db
      - redis
